channels:
- conda-forge
dependencies:
- python >=3.10
- bokeh
- coverage
- cython
- future
- h5py
- holoviews
- ipykernel
- ipython
- ipyparallel
- jupyter
- matplotlib
- mypy
- nose
- numpy
- numpydoc
- opencv
- peakutils
- pims
- psutil
- pynwb
- pyqtgraph
- scikit-image >=0.19.0
- scikit-learn
- scipy
- tensorflow >= 2.4.0
- tifffile
- tk
- tqdm
- yapf
- z5py
